/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Home1RouteImport } from './routes/home1'
import { Route as Home2RouteImport } from './routes/home2'
import { Route as Home3RouteImport } from './routes/home3'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Home1Route = Home1RouteImport.update({
  id: '/home1',
  path: '/home1',
  getParentRoute: () => rootRouteImport,
} as any)
const Home2Route = Home2RouteImport.update({
  id: '/home2',
  path: '/home2',
  getParentRoute: () => rootRouteImport,
} as any)
const Home3Route = Home3RouteImport.update({
  id: '/home3',
  path: '/home3',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home1': typeof Home1Route
  '/home2': typeof Home2Route
  '/home3': typeof Home3Route
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home1': typeof Home1Route
  '/home2': typeof Home2Route
  '/home3': typeof Home3Route
  '/shop/$slug': typeof ShopSlugRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home1': typeof Home1Route
  '/home2': typeof Home2Route
  '/home3': typeof Home3Route
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home1' | '/home2' | '/home3' | '/shop/$slug' | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home1' | '/home2' | '/home3' | '/shop/$slug' | '/shop'
  id:
    '__root__' | '/' | '/home1' | '/home2' | '/home3' | '/shop/$slug' | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Home1Route: typeof Home1Route
  Home2Route: typeof Home2Route
  Home3Route: typeof Home3Route
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home1': {
      id: '/home1'
      path: '/home1'
      fullPath: '/home1'
      preLoaderRoute: typeof Home1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home2': {
      id: '/home2'
      path: '/home2'
      fullPath: '/home2'
      preLoaderRoute: typeof Home2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home3': {
      id: '/home3'
      path: '/home3'
      fullPath: '/home3'
      preLoaderRoute: typeof Home3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Home1Route: Home1Route,
  Home2Route: Home2Route,
  Home3Route: Home3Route,
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
